USE pc

SELECT CONVERT(decimal(7,2),AVG(SPEED)) AS avg_speed
FROM PC

SELECT maker, AVG(SCREEN) AS avg_screen
FROM LAPTOP JOIN PRODUCT ON LAPTOP.model = PRODUCT.model
GROUP BY maker

SELECT CONVERT(decimal(7,2),AVG(SPEED)) AS AvgSpeed
FROM LAPTOP
WHERE PRICE > 1000

SELECT PRODUCT.maker, CONVERT(decimal(7,2),AVG(PRICE)) AS avg_price
FROM PC join PRODUCT ON PC.model = product.model
WHERE PRODUCT.maker = 'A'
GROUP BY maker


SELECT PRODUCT.maker, CONVERT(decimal(7,2),AVG(PRICE)) AS avg_price
FROM 
  (SELECT PC.model, PC.price
   FROM PC
   UNION ALL
   SELECT LAPTOP.model, LAPTOP.price
   FROM LAPTOP) AS T1 JOIN PRODUCT ON T1.model = PRODUCT.model
WHERE maker = 'B'
GROUP BY maker

SELECT PC.speed, AVG(PC.price) AS avg_price
FROM PC
GROUP BY PC.speed

SELECT MAKER, COUNT(DISTINCT PC.code) AS num_of_pcs
FROM PC JOIN PRODUCT ON PC.model = PRODUCT.model
GROUP BY MAKER
HAVING COUNT(DISTINCT PC.code) >= 3




SELECT maker, price
FROM PC JOIN PRODUCT ON PC.model = PRODUCT.model
GROUP BY MAKER, price
HAVING price = (SELECT MAX(PC.price) AS max_price
                FROM PC)


SELECT PC.speed, AVG(PC.price) AS AvgPrice
FROM PC
WHERE PC.speed > 800
GROUP BY PC.speed

SELECT maker, CONVERT(decimal(7,2),AVG(PC.hd)) AS AvgHd
FROM PC JOIN PRODUCT ON PC.model = PRODUCT.model
WHERE PRODUCT.maker IN (SELECT PRODUCT.maker FROM PRINTER JOIN PRODUCT ON PRINTER.model = PRODUCT.model)
GROUP BY maker








USE ships

SELECT COUNT (DISTINCT CLASS) AS Num_classes
FROM CLASSES
WHERE CLASSES.TYPE = 'bb'

SELECT CLASS, AVG(NUMGUNS) AS AvgGuns
FROM CLASSES
WHERE CLASSES.TYPE = 'bb'
GROUP BY CLASSES.CLASS

SELECT AVG(NUMGUNS) AS AvgGuns
FROM CLASSES
WHERE CLASSES.TYPE = 'bb'

SELECT CLASSES.CLASS, MIN(SHIPS.LAUNCHED) AS first_y, MAX(SHIPS.LAUNCHED) AS last_y
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
GROUP BY CLASSES.CLASS

SELECT SHIPS.CLASS, COUNT (SHIPS.NAME) AS num_sunk
FROM SHIPS JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.RESULT = 'sunk'
GROUP BY SHIPS.CLASS

SELECT SHIPS.CLASS, COUNT (SHIPS.NAME) AS num_sunk
FROM SHIPS JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.RESULT = 'sunk'
GROUP BY SHIPS.CLASS
HAVING SHIPS.CLASS IN (SELECT CLASSES.CLASS FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
                        GROUP BY CLASSES.CLASS HAVING COUNT(DISTINCT SHIPS.NAME) >2 )

SELECT COUNTRY, CONVERT(decimal(7,2),AVG(BORE)) AS AvgBore
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
GROUP BY COUNTRY
