--USE FLIGHTS

-- --ex.1
--ALTER TABLE Flights
--ADD num_pass INT DEFAULT 0 WITH VALUES;

-- --ex.2
--ALTER TABLE Agencies
--ADD num_book INT DEFAULT 0 WITH VALUES;

-- ex.3

--CREATE TRIGGER trig_bookings
--ON Bookings
--AFTER INSERT
--AS 
--UPDATE FLIGHTS
--SET num_pass = num_pass + 1
--WHERE FLIGHTS.FNUMBER IN (SELECT FNUMBER FROM inserted WHERE STATUS = 1)
--UPDATE AGENCIES
--SET num_book = num_book + 1
--WHERE AGENCIES.NAME IN (SELECT AGENCIES.NAME FROM inserted);

--ex.4 

--CREATE TRIGGER trig_bookings2
--ON Bookings
--AFTER DELETE
--AS
--UPDATE FLIGHTS
--SET num_pass = num_pass - 1
--WHERE FLIGHTS.FNUMBER IN (SELECT FNUMBER FROM deleted)
--UPDATE AGENCIES
--SET num_book = num_book - 1
--WHERE AGENCIES.NAME IN (SELECT AGENCIES.NAME FROM deleted);

-- ex.5

--CREATE TRIGGER trig_bookings3
--ON Bookings
--AFTER UPDATE
--AS
--UPDATE FLIGHTS
--SET num_pass = num_pass + 1
--WHERE FLIGHTS.FNUMBER IN (SELECT FNUMBER FROM inserted WHERE STATUS = 1)
--UPDATE FLIGHTS
--SET num_pass = num_pass - 1
--WHERE FLIGHTS.FNUMBER IN (SELECT FNUMBER FROM deleted WHERE STATUS = 1);

--EXAMPLES TO TEST TRIGGERS
 
--SELECT *
--FROM FLIGHTS

--SELECT num_pass
--FROM FLIGHTS

--SELECT*
--FROM BOOKINGS

--INSERT INTO BOOKINGS
--VALUES ('YB400P', 'Travel Tour', 'TK', 'TK1037', 3, '2022-04-27', '2022-05-25', 400, 1)

--DELETE FROM BOOKINGS
--WHERE CODE LIKE 'YB400P'

--UPDATE BOOKINGS
--SET STATUS = 1
--WHERE CODE = 'YB298P'

--UPDATE BOOKINGS
--SET STATUS = 0
--WHERE CODE = 'YB298P'





