Use movies

--For check
--SELECT *
--FROM MOVIESTAR

-- 1.1
--INSERT INTO MOVIESTAR (NAME, GENDER, BIRTHDATE, ADDRESS)
--VALUES ('Nicole Kidman', 'F', '1967-06-20', DEFAULT);

--1.2
--DELETE FROM MOVIEEXEC
--WHERE NETWORTH < 30000000;

--1.3
--DELETE FROM MOVIESTAR
--WHERE MOVIESTAR.ADDRESS IS NULL

USE PC

--FOR CHECK
--SELECT *
--FROM LAPTOP JOIN PRODUCT ON LAPTOP.MODEL = PRODUCT.MODEL
--WHERE MAKER NOT IN (SELECT MAKER FROM PRINTER JOIN PRODUCT ON PRINTER.model = PRODUCT.model)

--SELECT PRODUCT.MODEL, PRODUCT.maker
--FROM PRODUCT JOIN LAPTOP ON PRODUCT.model = LAPTOP.model 
--WHERE PRODUCT.MAKER NOT IN (SELECT MAKER FROM PRINTER JOIN PRODUCT ON PRINTER.model = PRODUCT.model)

--2.1
--INSERT INTO PRODUCT (TYPE, MODEL, MAKER)
--VALUES ('pc', '1100', 'C')
--INSERT INTO PC (MODEL, CODE, SPEED, RAM, HD, CD, PRICE)
--VALUES ('1100', 12, 2400, 2048, 500, '52x', 299)

--2.2
--DELETE FROM PC
--WHERE MODEL LIKE '1100'

--2.3
--DELETE FROM LAPTOP
--WHERE MODEL IN (SELECT PRODUCT.MODEL 
                --FROM PRODUCT JOIN LAPTOP ON PRODUCT.model = LAPTOP.model 
                --WHERE PRODUCT.MAKER NOT IN (SELECT MAKER FROM PRINTER JOIN PRODUCT ON PRINTER.model = PRODUCT.model))



--2.4
--UPDATE PRODUCT
--SET MAKER='A'
--WHERE MAKER LIKE 'B'

--2.5
--UPDATE PC
--SET PRICE = PRICE / 2, HD = HD + 20

--2.6
--UPDATE LAPTOP
--SET SCREEN = SCREEN - 1
--WHERE LAPTOP.MODEL IN (SELECT LAPTOP.MODEL FROM LAPTOP JOIN PRODUCT ON LAPTOP.MODEL = PRODUCT.MODEL WHERE PRODUCT.MAKER LIKE 'B')

USE ships

--FOR CHECK
--SELECT *
--FROM SHIPS

--3.1
--INSERT INTO CLASSES
--VALUES('Nelson', 'bb', 'Gt.Britain', 9, 16, 34000);

--INSERT INTO SHIPS
--VALUES ('Nelson', 'Nelson', 1927),
       --('Rodney', 'Nelson', 1927);

--3.2
--DELETE FROM SHIPS
--WHERE SHIPS.NAME IN (SELECT OUTCOMES.SHIP FROM OUTCOMES WHERE RESULT LIKE 'sunk')


--3.3
--UPDATE CLASSES
--SET BORE = BORE*2.5 , DISPLACEMENT= DISPLACEMENT * 0.9;

--DELETE FROM CLASSES
--WHERE CLASS LIKE 'Nelson'

