USE movies
SELECT NAME
FROM STARSIN JOIN MOVIESTAR ON STARNAME = NAME
WHERE MOVIETITLE = 'The Usual Suspects' AND gender = 'M';


SELECT STARNAME
FROM MOVIE JOIN STARSIN ON YEAR = MOVIEYEAR AND TITLE = MOVIETITLE
WHERE YEAR = 1995 AND STUDIONAME = 'MGM';

SELECT distinct NAME
FROM MOVIE JOIN MOVIEEXEC ON PRODUCERC# = CERT#
WHERE STUDIONAME = 'MGM';

SELECT M2.TITLE
FROM MOVIE AS M1 CROSS JOIN MOVIE AS M2
WHERE M1.TITLE = 'Star Wars' AND M1.LENGTH < M2.LENGTH;

SELECT EXEC2.NAME
FROM MOVIEEXEC AS EXEC1 CROSS JOIN MOVIEEXEC AS EXEC2
WHERE EXEC1.NAME = 'Stephen Spielberg' AND EXEC1.NETWORTH < EXEC2.NETWORTH


USE pc

SELECT MAKER, SPEED
FROM product JOIN laptop ON PRODUCT.model = LAPTOP.MODEL
WHERE HD >= 9;

/*SELECT P1.model
FROM PRODUCT AS P1 JOIN PRODUCT AS P2 ON P1.maker = P2.maker
WHERE P1.maker = 'B' AND P2.maker = 'B';*/

SELECT PRODUCT.model, PRICE
FROM PRODUCT JOIN LAPTOP ON PRODUCT.model = LAPTOP.model
WHERE MAKER = 'B'
UNION
SELECT PRODUCT.model, PRICE
FROM PRODUCT JOIN PC ON PRODUCT.model = PC.model
WHERE maker = 'B'
UNION
SELECT PRODUCT.model, PRICE
FROM PRODUCT JOIN PRINTER ON PRODUCT.model = PRINTER.model
WHERE MAKER = 'B';

SELECT MAKER
FROM product
WHERE TYPE = 'Laptop'
EXCEPT
SELECT MAKER
FROM product
WHERE TYPE = 'PC';


SELECT DISTINCT P1.hd
FROM PC AS P1 JOIN PC AS P2 ON P1.hd = P2.hd
WHERE P1.code != P2.code

SELECT PC1.model, PC2.model
FROM PC AS PC1 JOIN PC AS PC2 ON PC1.speed = PC2.speed AND PC1.ram = PC2.ram
WHERE PC1.model < PC2.model;

SELECT DISTINCT PRODUCT.maker
FROM PRODUCT JOIN PC AS PC1 ON PRODUCT.model = PC1.model JOIN PC AS PC2 ON PC1.model!=PC2.model
WHERE PC1.speed >= 400 AND PC2.speed>=400;

/*SELECT maker
FROM PRODUCT JOIN PC AS P1 ON PRODUCT.model = P1.model
WHERE P1.speed >= 400
INTERSECT
SELECT 
FROM PRODUCT JOIN P
WHERE*/

USE ships
SELECT NAME
FROM ships JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE DISPLACEMENT > 50000;

SELECT NAME, DISPLACEMENT, NUMGUNS
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE BATTLE = 'Guadalcanal';

SELECT COUNTRY
FROM CLASSES
WHERE TYPE = 'bb'
INTERSECT
SELECT COUNTRY
FROM CLASSES
WHERE TYPE = 'bc';

SELECT DISTINCT OUTCOMES.SHIP
FROM BATTLES AS B1 JOIN BATTLES AS B2 ON B1.DATE < B2.DATE JOIN OUTCOMES ON B1.NAME = BATTLE
WHERE RESULT = 'damaged'

/*SELECT 
FROM CLASSES
WHERE TYPE = 'bb'
INTERSECT
SELECT COUNTRY
FROM CLASSES
WHERE TYPE = 'bc';*/

SELECT OUTCOMES.SHIP
FROM OUTCOMES
WHERE OUTCOMES.RESULT = 'damaged'






